export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';
export const FETCH_MORE_BOOKS_SUCCESS = 'FETCH_MORE_BOOKS_SUCCESS';
