export const ADD_TO_READING_LIST = 'ADD_TO_READING_LIST';
export const DELETE_FROM_READING_LIST = 'DELETE_FROM_READING_LIST';
export const TOGGLE_READING_BOOK = 'TOGGLE_READING_BOOK';
export const RATE_BOOK = 'RATE_BOOK';
